#pragma once

/* Auto-generated by WinVersion - Nullriver Software - http://www.nullriver.com */

#define MAJOR 1
#define MINOR 0
#define RELEASE 0
#define BUILD 61
#define VERSION_STRING "1.0.0.61"
